version: "4"
services:
  server:
    build: .
    command: npm run dev
    container_name: server
    ports:
      - "${HTTP_PORT}:8000"
    volumes:
      - ./:/var/www/
      - /var/www/vendor
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - app-network
  mysql:
    image: mariadb:latest
    container_name: mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306

networks:
  app-network:
    driver: bridge

    # volumes:
    #   - ./mysql/init.sql:/data/application/init.sql
    #   - mysql_data:/var/lib/mysql
  # client:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.node
  #   container_name: client
  #   volumes:
  #     - ./:/var/www/
  #     - /var/www/node_modules
  #   depends_on:
  #     - "server"
# volumes:
#   mysql_data:
