version: "4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./:/var/www/html/
    networks:
      - app-network
  
  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  mysql:
    image: mariadb:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
